# Generated by Django 3.2.5 on 2021-07-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.CharField(max_length=200)),
                ('item_status', models.CharField(choices=[('BOUGHT', 'BOUGHT'), ('NOT-AVAILABLE', 'NOT-AVAILABLE'), ('BUY', 'BUY')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.profile')),
            ],
        ),
    ]
