# Generated by Django 3.2.5 on 2021-07-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylist',
            old_name='user',
            new_name='customer',
        ),
    ]
