# Generated by Django 3.2.5 on 2021-07-07 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_mylist_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
