# Generated by Django 3.2.5 on 2021-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210707_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
